Repository Help-Us/cookhub, pull requests merged in 2024-03, with the labels that each got.

#2 [feat] - 메인 페이지 레이아웃 구현 #1
  src/app/layout.tsx
Labels: documentation, enhancement

#7 ✨ [feat] - Supabase 연결
  package.json
  src/app/testpage/page.tsx
  src/utils/supabase/server.ts
  yarn.lock
Labels: documentation, enhancement

#12 Mypage
  package.json
  src/app/globals.css
  src/app/mypage/page.tsx
  src/app/testpage/page.tsx
  src/components/mypage/MyPageContents.tsx
  src/components/mypage/MyPageScrap.tsx
  src/types/database.type.ts
  src/types/index.ts
  yarn.lock
Labels: documentation, enhancement

#14 [feat] - 검색창 UI 구현
  src/app/globals.css
  src/app/page.tsx
  src/components/layout/SearchBox.tsx
Labels: documentation, enhancement

#15 #13 Category 페이지 UI 완료
  src/app/category/page.tsx
  src/app/globals.css
  src/components/category/CategoryBar.tsx
  src/components/category/FilteredFoods.tsx
  tailwind.config.ts
Labels: documentation, enhancement

#17 Detail - 상세페이지 컴포넌트 UI 구현
  next.config.mjs
  package.json
  src/app/detail/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/detail/Comments.tsx
  src/components/detail/Cooking.tsx
  src/components/detail/FoodName.tsx
  src/components/detail/Ingredients.tsx
  src/components/detail/Nutrient.tsx
  tailwind.config.ts
  yarn.lock
Labels: documentation, enhancement

#18 #16 추천 레시피 기능 구현
  package.json
  src/app/page.tsx
  src/components/layout/SearchBox.tsx
  src/components/mainpage/RecommendRecipes.tsx
  src/types/index.ts
  tailwind.config.ts
  yarn.lock
Labels: documentation, enhancement

#24 Mypage
  package.json
  src/api/supabase/supabase.ts
  src/app/globals.css
  src/app/layout.tsx
  src/app/mypage/page.tsx
  src/app/provider.tsx
  src/components/Navigation.tsx
  src/components/mypage/MyPageContents.tsx
  src/components/mypage/MyPageImage.tsx
  src/components/mypage/MyPageScrap.tsx
  src/components/styles/style.css
  src/types/database.type.ts
  src/types/index.ts
  tsconfig.json
  yarn.lock
Labels: documentation, enhancement

#30 [feat] - 메인페이지 기능 구현
  src/app/page.tsx
  src/components/layout/SearchBox.tsx
  src/components/mainpage/RecommendRecipe.tsx
  src/components/mainpage/RecommendRecipes.tsx
  src/types/database.type.ts
  src/types/index.ts
Labels: documentation, enhancement

#31 #22 카테고리 페이지 기능구현
  .gitignore
  next.config.mjs
  src/api/supabase/supabase.ts
  src/app/category/[search]/page.tsx
  src/app/category/page.tsx
  src/app/layout.tsx
  src/components/category/Category.tsx
  src/components/category/CategoryBar.tsx
  src/components/category/FilteredFoods.tsx
  src/components/layout/SearchBox.tsx
  src/types/index.ts
Labels: documentation, enhancement

#32 Detail
  next.config.mjs
  src/app/detail/[id]/page.tsx
  src/app/detail/page.tsx
  src/components/detail/Comments.tsx
  src/components/detail/FoodName.tsx
  src/components/detail/Ingredients.tsx
  src/components/detail/Nutrient.tsx
  src/utils/supabase/server.ts
  tailwind.config.ts
Labels: documentation, enhancement

#34 [feat] - 로그인/회원가입 페이지 UI 제작
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/assets/googleLogo.png
  src/assets/kakaoLogo.png
  src/assets/naverLogo.jpg
  src/components/loginPage/LoginBtn.tsx
  src/components/loginPage/PageTitle.tsx
  src/components/loginPage/SocialLoginBtn.tsx
  src/components/loginPage/UserInfoInputForm.tsx
  src/components/styles/style.css
Labels: documentation, enhancement

#37 Category 페이지 기능 구현
  src/api/supabase/supabase.ts
  src/app/category/[search]/page.tsx
  src/assets/images/Cookhub_Logo.png.png
  src/components/Navigation.tsx
  src/components/category/Category.tsx
  src/components/category/FilteredFoods.tsx
  src/components/layout/SearchBox.tsx
Labels: documentation, enhancement

#38 헤더 UI 구현
  src/assets/images/Cookhub_Logo.png
  src/components/Navigation.tsx
  src/components/category/FilteredFoods.tsx
Labels: documentation, enhancement

#39 [feat] - 일반 로그인/회원가입 기능 구현
  package.json
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/shared/zustand/userInfoStore.ts
  src/utils/supabase/checkLoginUser.ts
  yarn.lock
Labels: documentation, enhancement

#47 Scrap 상태 실시간 반영
  src/api/supabase/supabase.ts
  src/components/detail/Scrap.tsx
  src/constants/QueryKeys.ts
  src/hooks/mutateScrap.ts
  src/hooks/useQueryScrap.ts
Labels: documentation, enhancement

#51 Detail
  README.md
  next.config.mjs
  src/api/supabase/supabase.ts
  src/app/detail/[id]/page.tsx
  src/app/layout.tsx
  src/components/Footer.tsx
  src/components/detail/Comments.tsx
  src/components/detail/Cooking.tsx
  src/components/detail/FoodName.tsx
  src/components/detail/Ingredients.tsx
  tailwind.config.ts
Labels: documentation, enhancement

#52 Category 부가 기능 구현
  src/api/supabase/supabase.ts
  src/app/category/[search]/page.tsx
  src/app/detail/[id]/page.tsx
  src/app/layout.tsx
  src/components/category/Category.tsx
  src/components/category/FilteredFoods.tsx
  src/components/detail/Scrap.tsx
  src/constants/QueryKeys.ts
  src/hooks/mutateScrap.ts
  src/hooks/useQuery.ts
  src/hooks/useQueryScrap.ts
Labels: documentation, enhancement

#54 Detail
  src/api/supabase/supabase.ts
  src/components/detail/Comments.tsx
Labels: documentation, enhancement

#56 Mypage
  next.config.mjs
  public/imges/defaultImage.png
  src/api/supabase/supabase.ts
  src/app/mypage/page.tsx
  src/components/hooks/useQueryKey.ts
  src/components/mypage/MyPageContents.tsx
  src/components/mypage/MyPageImage.tsx
  src/components/mypage/MyPageUpload.tsx
  src/components/styles/style.css
  src/types/index.ts
  src/utils/supabase/checkLoginUser.ts
  yarn.lock
Labels: documentation, enhancement

#58 [✅/add] - 유저 댓글 목록 조회 및 게시물 이동
  next.config.mjs
  src/components/detail/Comments.tsx
  src/components/mypage/MyPageContents.tsx
  src/components/mypage/MyPageScrap.tsx
  src/components/mypage/MyPageUpload.tsx
  src/components/styles/style.css
Labels: documentation, enhancement

#63 배포를 위한 dev 1차 통합(dev -> loginPage)
  src/components/detail/Comments.tsx
  src/components/mypage/MyPageContents.tsx
  src/components/mypage/MyPageScrap.tsx
  src/components/mypage/MyPageUpload.tsx
  src/components/styles/style.css
Labels: documentation, enhancement

#64 Login page
  src/api/supabase/supabase.ts
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/app/signup/page.tsx
  src/assets/googleLogo.png
  src/assets/kakaoLogo.png
  src/assets/naverLogo.jpg
  src/components/Footer.tsx
  src/components/Navigation.tsx
  src/components/category/FilteredFoods.tsx
  src/components/detail/Comments.tsx
  src/components/detail/Cooking.tsx
  src/components/detail/FoodName.tsx
  src/components/detail/Ingredients.tsx
  src/components/detail/Nutrient.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Navigation.tsx
  src/components/loginPage/LoginBtn.tsx
  src/components/loginPage/PageTitle.tsx
  src/components/loginPage/SocialLoginBtn.tsx
  src/components/loginPage/UserInfoInputForm.tsx
  src/components/mypage/MyPageComments.tsx
  src/components/mypage/MyPageContents.tsx
  src/components/mypage/MyPageUpload.tsx
  src/components/styles/style.css
  src/shared/zustand/loginStateStore.ts
  src/utils/supabase/server.ts
  src/utils/userInfo/getUserInfoFromJSON.ts
Labels: documentation, enhancement

#66 🚑 [!HOTFIX/#65] - DB에서 유저 관리할 때 에러 메시지 alert 출력 처리
  src/utils/supabase/checkLoginUser.ts
Labels: bug, documentation, enhancement

#67 [feat] - 메인페이지 유효성 검사
  src/app/detail/[id]/page.tsx
  src/app/page.tsx
  src/assets/search.png
  src/components/layout/SearchBox.tsx
  src/components/mainpage/ClippingRecipe.tsx
  src/components/mainpage/RecommendRecipe.tsx
Labels: documentation, enhancement

#68 Category 에러 수정
  src/components/category/FilteredFoods.tsx
  src/hooks/useQuery.ts
Labels: documentation, enhancement

#70 [!HOTFIX] - 배포를 위한 HOTFIX 수정
  src/components/category/FilteredFoods.tsx
  src/components/mypage/MyPageContents.tsx
  src/utils/userInfo/getUserInfoFromJSON.ts
Labels: bug, documentation, enhancement

#73 [!HOTFIX] - Vercel 배포 에러 해결 시도(2)
  package.json
  yarn.lock
Labels: bug, documentation

#75 Detail
  README.md
  src/api/supabase/supabase.ts
Labels: documentation

#76 리드미 수정
  README.md
Labels: documentation, enhancement

#77 Category 수정
  src/app/layout.tsx
  src/components/detail/Scrap.tsx
Labels: documentation, enhancement

#79 Mypage
  src/components/mypage/MyPageContents.tsx
  src/components/mypage/MyPageUpload.tsx
  src/components/styles/style.css
Labels: documentation, enhancement

#80 Mypage
  src/components/mypage/MyPageContents.tsx
  src/components/mypage/MyPageUpload.tsx
Labels: documentation, enhancement
